name: note_app
description: A new Note App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.4
  go_router: ^11.1.3
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets\icons\keep_up_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/image/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
